name: 'Ansible'
description: 'Runs an Ansible playbook'
inputs:
  key:
    description: "String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)"
    required: false
  playbook:
    description: 'Ansible playbook to run'
    required: true
    default: playbook.yml
  inventory:
    description: 'Ansible inventory to use'
    required: true
    default: localhost
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key }}
    - ${{ inputs.playbook }}
    - ${{ inputs.inventory }}